steps:
- label: ":docker: configure image tag"
  key: tag:create
  commands:
  - TAGI=$BUILDKITE_BUILD_ID
  - buildkite-agent meta-data set 'TAG'  $BUILDKITE_BUILD_ID
  - buildkite-agent step update "label" "TAG=$BUILDKITE_BUILD_ID \:sunglasses:\:sunglasses:"
