steps:
- label: ":docker: configure image tag"
  key: tag:create
  commands:
  - TAGI=$(BUILDKITE_BUILD_ID)
  - buildkite-agent meta-data set 'TAG' '$(TAGI)'
  - buildkite-agent step update "label" "TAG=\'$(TAGI)\' \:sunglasses:\:sunglasses:"
