steps:
- label: ":docker: configure image tag"
  key: tag:create
  commands:
  - TAGI=$(date)
  - buildkite-agent meta-data set 'TAG' '$(TAGI)'
  - buildkite-agent step update "label" " 😎 :sunglasses: TAG=${TAGI}"
